package antuere.how_are_you.presentation.base.ui_theme

import androidx.compose.ui.graphics.Color

/*
Colors for SVG in drawing res:
- Fill color: C2C2C2
- Board: 7A7A7A
 */

// Default light theme
val default_light_theme_primary = Color(0xFF026D92)
val default_light_theme_primaryContainer = Color(0xFF7EC6E0)
val default_light_theme_onPrimaryContainer = Color(0xFF002B3A)
val default_light_theme_onPrimary = Color(0xFFF8F7F2)
val default_light_theme_tertiary = Color(0xFFDFDED9)
val default_light_theme_secondary = Color(0xFF4C738A)
val default_light_theme_secondaryContainer = Color(0xFFA3D6EB)
val default_light_theme_onSecondaryContainer = Color(0xFF002B3A)
val default_light_theme_onSecondary = Color(0xFF5C8A9C)
val default_light_theme_surface = Color(0xFFCCEEFA)
val default_light_theme_surfaceVariant = Color(0xFFBDCDD6)
val default_light_theme_onSurface = Color(0xFF002B3A)
val default_light_theme_onSurfaceVariant = Color(0xFF505C61)
val default_light_theme_background = Color(0xFFF8F7F2)
val default_light_theme_onBackground = Color(0xFF002B3A)
val default_light_theme_outline = Color(0xFF71787D)
val default_light_theme_outline_variant = Color(0xFF9A9C9C)
val default_light_theme_error = Color(0xFFCF0909)
val default_light_theme_inverseSurface = Color(0xFF07394B)

// Default dark theme XXX
val default_dark_theme_primary = Color(0xFFB7E6FA)
val default_dark_theme_primaryContainer = Color(0xFF5EA0BB)
val default_dark_theme_onPrimaryContainer = Color(0xFFF8F7F2)
val default_dark_theme_onPrimary = Color(0xFF2E2D31)
val default_dark_theme_tertiary = Color(0xFF097499)
val default_dark_theme_secondary = Color(0xFFCCEEFA)
val default_dark_theme_secondaryContainer = Color(0xFF52819C)
val default_dark_theme_onSecondaryContainer = Color(0xFFFDFDF9)
val default_dark_theme_onSecondary = Color(0xFF5C8A9C)
val default_dark_theme_surface = Color(0xFF104B61)
val default_dark_theme_surfaceVariant = Color(0xFF033D52)
val default_dark_theme_onSurface = Color(0xFFE3F4FA)
val default_dark_theme_onSurfaceVariant = Color(0xFF7BA1AD)
val default_dark_theme_background = Color(0xFF1C1B1F)
val default_dark_theme_onBackground = Color(0xFFF4FBFD)
val default_dark_theme_outline = Color(0xFFDFDED9)
val default_dark_theme_outline_variant = Color(0xFFB8B8B8)
val default_dark_theme_error = Color(0xFFCF0909)
val default_dark_theme_inverseSurface = Color(0xFF003041)

// Red light theme
val red_light_theme_primary = Color(0xFF910112)
val red_light_theme_primaryContainer = Color(0xFFe07e7e)
val red_light_theme_onPrimaryContainer = Color(0xFF002B3A)
val red_light_theme_onPrimary = Color(0xFFF8F7F2)
val red_light_theme_tertiary = Color(0xFFDFDED9)
val red_light_theme_secondary = Color(0xFF8a4c4c)
val red_light_theme_secondaryContainer = Color(0xFFeba2a2)
val red_light_theme_onSecondaryContainer = Color(0xFF3b0000)
val red_light_theme_onSecondary = Color(0xFF9c5c5c)
val red_light_theme_surface = Color(0xFFfacdcd)
val red_light_theme_surfaceVariant = Color(0xFFd6bcbc)
val red_light_theme_onSurface = Color(0xFF002B3A)
val red_light_theme_onSurfaceVariant = Color(0xFF505C61)
val red_light_theme_background = Color(0xFFF8F7F2)
val red_light_theme_onBackground = Color(0xFF3b0000)
val red_light_theme_outline = Color(0xFF71787D)
val red_light_theme_outline_variant = Color(0xFF9A9C9C)
val red_light_theme_error = Color(0xFFCF0909)
val red_light_theme_inverseSurface = Color(0xFF4a0707)

// Red dark theme XXX
val red_dark_theme_primary = Color(0xFF026D92)
val red_dark_theme_primaryContainer = Color(0xFF7EC6E0)
val red_dark_theme_onPrimaryContainer = Color(0xFF002B3A)
val red_dark_theme_onPrimary = Color(0xFFF8F7F2)
val red_dark_theme_secondary = Color(0xFF4C738A)
val red_dark_theme_secondaryContainer = Color(0xFFA3D6EB)
val red_dark_theme_onSecondaryContainer = Color(0xFF002B3A)
val red_dark_theme_tertiary = Color(0xFFDFDED9)
val red_dark_theme_onSecondary = Color(0xFF5C8A9C)
val red_dark_theme_surface = Color(0xFFCCEEFA)
val red_dark_theme_surfaceVariant = Color(0xFFBDCDD6)
val red_dark_theme_onSurface = Color(0xFF002B3A)
val red_dark_theme_onSurfaceVariant = Color(0xFF505C61)
val red_dark_theme_background = Color(0xFFF8F7F2)
val red_dark_theme_onBackground = Color(0xFF002B3A)
val red_dark_theme_outline = Color(0xFF71787D)
val red_dark_theme_outline_variant = Color(0xFF9A9C9C)
val red_dark_theme_error = Color(0xFFCF0909)
val red_dark_theme_inverseSurface = Color(0xFF4a0707)

// Green light theme XXX
val green_light_theme_primary = Color(0xFF026D92)
val green_light_theme_primaryContainer = Color(0xFF7EC6E0)
val green_light_theme_onPrimaryContainer = Color(0xFF002B3A)
val green_light_theme_onPrimary = Color(0xFFF8F7F2)
val green_light_theme_tertiary = Color(0xFFDFDED9)
val green_light_theme_secondary = Color(0xFF4C738A)
val green_light_theme_secondaryContainer = Color(0xFFA3D6EB)
val green_light_theme_onSecondaryContainer = Color(0xFF002B3A)
val green_light_theme_onSecondary = Color(0xFF5C8A9C)
val green_light_theme_surface = Color(0xFFCCEEFA)
val green_light_theme_surfaceVariant = Color(0xFFBDCDD6)
val green_light_theme_onSurface = Color(0xFF002B3A)
val green_light_theme_onSurfaceVariant = Color(0xFF505C61)
val green_light_theme_background = Color(0xFFF8F7F2)
val green_light_theme_onBackground = Color(0xFF002B3A)
val green_light_theme_outline = Color(0xFF71787D)
val green_light_theme_outline_variant = Color(0xFF9A9C9C)
val green_light_theme_error = Color(0xFFCF0909)
val green_light_theme_inverseSurface = Color(0xFF002B3A)

// Green dark theme XXX
val green_dark_theme_primary = Color(0xFF026D92)
val green_dark_theme_primaryContainer = Color(0xFF7EC6E0)
val green_dark_theme_onPrimaryContainer = Color(0xFF002B3A)
val green_dark_theme_onPrimary = Color(0xFFF8F7F2)
val green_dark_theme_tertiary = Color(0xFFDFDED9)
val green_dark_theme_secondary = Color(0xFF4C738A)
val green_dark_theme_secondaryContainer = Color(0xFFA3D6EB)
val green_dark_theme_onSecondaryContainer = Color(0xFF002B3A)
val green_dark_theme_onSecondary = Color(0xFF5C8A9C)
val green_dark_theme_surface = Color(0xFFCCEEFA)
val green_dark_theme_surfaceVariant = Color(0xFFBDCDD6)
val green_dark_theme_onSurface = Color(0xFF002B3A)
val green_dark_theme_onSurfaceVariant = Color(0xFF505C61)
val green_dark_theme_background = Color(0xFFF8F7F2)
val green_dark_theme_onBackground = Color(0xFF002B3A)
val green_dark_theme_outline = Color(0xFF71787D)
val green_dark_theme_outline_variant = Color(0xFF9A9C9C)
val green_dark_theme_error = Color(0xFFCF0909)
val green_dark_theme_inverseSurface = Color(0xFF002B3A)

// Yellow light theme XXX
val yellow_light_theme_primary = Color(0xFF026D92)
val yellow_light_theme_primaryContainer = Color(0xFF7EC6E0)
val yellow_light_theme_onPrimaryContainer = Color(0xFF002B3A)
val yellow_light_theme_onPrimary = Color(0xFFF8F7F2)
val yellow_light_theme_tertiary = Color(0xFFDFDED9)
val yellow_light_theme_secondary = Color(0xFF4C738A)
val yellow_light_theme_secondaryContainer = Color(0xFFA3D6EB)
val yellow_light_theme_onSecondaryContainer = Color(0xFF002B3A)
val yellow_light_theme_onSecondary = Color(0xFF5C8A9C)
val yellow_light_theme_surface = Color(0xFFCCEEFA)
val yellow_light_theme_surfaceVariant = Color(0xFFBDCDD6)
val yellow_light_theme_onSurface = Color(0xFF002B3A)
val yellow_light_theme_onSurfaceVariant = Color(0xFF505C61)
val yellow_light_theme_background = Color(0xFFF8F7F2)
val yellow_light_theme_onBackground = Color(0xFF002B3A)
val yellow_light_theme_outline = Color(0xFF71787D)
val yellow_light_theme_outline_variant = Color(0xFF9A9C9C)
val yellow_light_theme_error = Color(0xFFCF0909)
val yellow_light_theme_inverseSurface = Color(0xFF002B3A)

// Yellow dark theme XXX
val yellow_dark_theme_primary = Color(0xFF026D92)
val yellow_dark_theme_primaryContainer = Color(0xFF7EC6E0)
val yellow_dark_theme_onPrimaryContainer = Color(0xFF002B3A)
val yellow_dark_theme_onPrimary = Color(0xFFF8F7F2)
val yellow_dark_theme_tertiary = Color(0xFFDFDED9)
val yellow_dark_theme_secondary = Color(0xFF4C738A)
val yellow_dark_theme_secondaryContainer = Color(0xFFA3D6EB)
val yellow_dark_theme_onSecondaryContainer = Color(0xFF002B3A)
val yellow_dark_theme_onSecondary = Color(0xFF5C8A9C)
val yellow_dark_theme_surface = Color(0xFFCCEEFA)
val yellow_dark_theme_surfaceVariant = Color(0xFFBDCDD6)
val yellow_dark_theme_onSurface = Color(0xFF002B3A)
val yellow_dark_theme_onSurfaceVariant = Color(0xFF505C61)
val yellow_dark_theme_background = Color(0xFFF8F7F2)
val yellow_dark_theme_onBackground = Color(0xFF002B3A)
val yellow_dark_theme_outline = Color(0xFF71787D)
val yellow_dark_theme_outline_variant = Color(0xFF9A9C9C)
val yellow_dark_theme_error = Color(0xFFCF0909)
val yellow_dark_theme_inverseSurface = Color(0xFF002B3A)

val color_dark_green = Color(0xFF06751F)
val color_red = Color(0xFFDF1919)

val color_bad_day = Color(0xFFFF2E3F)
val color_calendar_header = Color(0xFFFD5462)

val TealMain = Color(0xFF008394)
val Teal200 = Color(0xFF03DAC5)

val Teal700 = Color(0xFF018786)

val Gray800 = Color(0x80000000)
val Gray400 = Color(0xFF4E4D4D)
